#!/usr/bin/env ansible-playbook

- name: Build sflow meta.yml
  hosts: localhost
  roles:
    - sflow_build
  tags:
    - build
    - sflow_build
    - sflow

- name: Build bird.conf
  hosts: localhost
  roles:
    - bird_build
  tags:
    - build
    - bird_build
    - bird

- name: Build eos config
  hosts: localhost
  roles:
    - eos_build
  tags:
    - build
    - eos_build
    - eos


- name: Push sflow config
  hosts: sflow
  roles:
    - sflow_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - sflow_push
    - sflow

- name: Push bird config
  hosts: bird
  serial: 1
  any_errors_fatal: true
  roles:
    - bird_push
  tags:
    - push
    - bird_push
    - bird

- name: Push eos config
  hosts: eos
  serial: 1
  any_errors_fatal: true
  roles:
    - eos_push
  vars:
    ansible_user: root
  tags:
    - push
    - eos_push
    - eos


- name: Reload bird
  hosts: bird
  serial: 1
  any_errors_fatal: true
  roles:
    - role: bird_reload
      when: engage_config|default(False)
  tags:
    - engage
    - bird_engage
    - bird

- name: Enable eos config
  hosts: eos
  connection: network_cli
  become: true
  become_method: enable
  serial: 1
  any_errors_fatal: true
  roles:
    - role: eos_configure
      when: engage_config|default(False)
  vars:
    ansible_network_os: "{{ engage_network_os }}"
  tags:
    - engage
    - eos_engage
    - eos
